### ISSUE TITLE
Bug in calculation

### ISSUE THREAD

**Issue by PeterJacob** [tinybike/weightedstats#2]
I installed the module via pip and was playing with the example as given 
>>> import weightedstats as ws
>>> my_data = [1, 2, 3, 4, 5]
>>> my_weights = [10, 1, 1, 1, 9]
>>> ws.weighted_median(my_data, weights=my_weights)

The output is 2.5. Seems correct since the median falls in between 2 and 3 here.

Then I changed the weights so 3 is the middle value:
>>> my_weights = [10, 1, 1, 1, 10]
>>> ws.weighted_median(my_data, weights=my_weights)

But now the output is still 2.5. This also happens when the weights are [1,1,1,1,1], but not when I omit the weights fully.

**Comment by amitport** [comment]
@PeterJacob, I'm also seeing this, did you found the issue/alternative package?

**Comment by tinybike** [comment]
@PeterJacob @amitport It turns out there was a missing absolute value in the weighted median calculation.  I fixed the error in https://github.com/tinybike/weightedstats/commit/6a6dfcb5a84993c33d0b09e8c6262b84e4018ba6 and have pushed a new version to https://pypi.org/project/weightedstats/.

Thank you both for finding and reporting this bug.  I apologize that it took me so long to respond.  I did not see the notification for this issue until now!
